# Generated by Django 4.2.1 on 2023-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('poster', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='app.catagory')),
            ],
        ),
    ]
