# Generated by Django 4.2.1 on 2023-05-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
