# Generated by Django 4.2.1 on 2023-05-27 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_movie_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('link', models.FilePathField(blank=True, null=True, path='media\\series', recursive=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.FilePathField(blank=True, null=True, path='media\\images', recursive=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='series_name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AddField(
            model_name='movie',
            name='episodes',
            field=models.ManyToManyField(blank=True, to='app.episode'),
        ),
    ]
