# Generated by Django 4.2.1 on 2023-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.FilePathField(null=True, path=None, recursive=None),
        ),
    ]
