# Generated by Django 4.2.1 on 2023-05-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.FilePathField(blank=True, null=True, path='media', recursive=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='app.catagory'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.series'),
        ),
    ]
